package com.codecrafthub.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;

/**
 * Course entity representing a course in the learning platform.
 *
 * This class contains all the information needed to track a course's progress
 * and status in the learning platform.
 *
 * Fields:
 * - id: Unique identifier for the course (UUID format)
 * - name: Title of the course
 * - description: Description of the course content
 * - targetDate: Expected date to complete the course
 * - status: Current status of the course (NOT_STARTED, IN_PROGRESS, COMPLETED)
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Course {

    private String id;

    private String name;

    private String description;

    @JsonFormat(pattern = "yyyy-MM-dd")
    private LocalDate targetDate;

    private CourseStatus status;

    /**
     * Constructor for creating a course without an ID (used during creation).
     * The ID will be generated by the service layer.
     */
    public Course(String name, String description, LocalDate targetDate, CourseStatus status) {
        this.name = name;
        this.description = description;
        this.targetDate = targetDate;
        this.status = status;
    }
}
